FROM node:12.16.1 as builder

WORKDIR /app
COPY . /app/

RUN npm install -g yarn
RUN yarn install

RUN yarn build

FROM nginx:1.16
#:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
# CMD [“nginx”, “-g”, “daemon off;”]
